import type { Project, User, Order, KycRecord, MarketplaceFees, Payout, AuditLog, PromoterBalance } from "./types"

export const mockProjects: Project[] = [
  {
    id: "1",
    name: "Torre Residencial Madrid Centro",
    category: "Real Estate",
    location: "Madrid, España",
    image: "/modern-residential-tower-madrid.jpg",
    pricePerTokenUSDT: 100,
    totalSupply: 10000,
    availableSupply: 7500,
    minBuy: 10,
    maxBuy: 500,
    apyEstimated: 8.5,
    riskNotes: "Inversión en activo inmobiliario. Riesgo medio. Sujeto a fluctuaciones del mercado inmobiliario.",
    description:
      "Proyecto de tokenización de torre residencial de lujo en el centro de Madrid. Edificio de 20 plantas con 80 unidades residenciales premium.",
    documents: [
      { id: "1", name: "Prospecto de Inversión", type: "PDF", url: "#" },
      { id: "2", name: "Valuación Independiente", type: "PDF", url: "#" },
      { id: "3", name: "Términos y Condiciones", type: "PDF", url: "#" },
    ],
    status: "approved",
    ownerPromoterId: "promoter-1",
    salesUSDT: 250000,
    buyersCount: 25,
    featured: true,
    featuredScore: 95,
    featuredTag: "Top",
    highlightUntil: "2025-12-31T23:59:59Z",
  },
  {
    id: "2",
    name: "Parque Solar Andalucía",
    category: "Energy",
    location: "Sevilla, España",
    image: "/solar-panel-farm-renewable-energy.jpg",
    pricePerTokenUSDT: 50,
    totalSupply: 20000,
    availableSupply: 15000,
    minBuy: 20,
    maxBuy: 1000,
    apyEstimated: 12.3,
    riskNotes: "Inversión en energía renovable. Riesgo medio-bajo. Ingresos garantizados por contratos PPA.",
    description:
      "Parque solar fotovoltaico de 50MW con contratos de compra de energía a largo plazo. Generación estimada de 80 GWh anuales.",
    documents: [
      { id: "1", name: "Análisis Técnico", type: "PDF", url: "#" },
      { id: "2", name: "Contratos PPA", type: "PDF", url: "#" },
      { id: "3", name: "Proyección Financiera", type: "PDF", url: "#" },
    ],
    status: "approved",
    ownerPromoterId: "promoter-2",
    salesUSDT: 250000,
    buyersCount: 50,
    featured: true,
    featuredScore: 90,
    featuredTag: "Alta demanda",
    highlightUntil: "2025-12-31T23:59:59Z",
  },
  {
    id: "3",
    name: "Hotel Boutique Barcelona",
    category: "Hospitality",
    location: "Barcelona, España",
    image: "/luxury-boutique-hotel-barcelona.jpg",
    pricePerTokenUSDT: 200,
    totalSupply: 5000,
    availableSupply: 3200,
    minBuy: 5,
    maxBuy: 250,
    apyEstimated: 10.8,
    riskNotes: "Inversión en sector hotelero. Riesgo medio. Sujeto a ocupación y temporada turística.",
    description:
      "Hotel boutique de 5 estrellas con 45 habitaciones en el corazón del Barrio Gótico. Incluye restaurante gourmet y spa.",
    documents: [
      { id: "1", name: "Plan de Negocio", type: "PDF", url: "#" },
      { id: "2", name: "Estudio de Mercado", type: "PDF", url: "#" },
      { id: "3", name: "Licencias y Permisos", type: "PDF", url: "#" },
    ],
    status: "approved",
    ownerPromoterId: "promoter-1",
    salesUSDT: 360000,
    buyersCount: 18,
    featured: true,
    featuredScore: 85,
    featuredTag: "Nuevo",
  },
  {
    id: "4",
    name: "Centro Logístico Valencia",
    category: "Logistics",
    location: "Valencia, España",
    image: "/modern-logistics-warehouse-center.jpg",
    pricePerTokenUSDT: 75,
    totalSupply: 15000,
    availableSupply: 12000,
    minBuy: 15,
    maxBuy: 750,
    apyEstimated: 9.2,
    riskNotes: "Inversión en infraestructura logística. Riesgo bajo. Contratos de arrendamiento a largo plazo.",
    description:
      "Centro logístico de última generación con 50,000 m² de almacenamiento. Ubicación estratégica cerca del puerto.",
    documents: [
      { id: "1", name: "Contratos de Arrendamiento", type: "PDF", url: "#" },
      { id: "2", name: "Certificaciones", type: "PDF", url: "#" },
      { id: "3", name: "Análisis de Rentabilidad", type: "PDF", url: "#" },
    ],
    status: "pending",
    ownerPromoterId: "promoter-2",
    salesUSDT: 0,
    buyersCount: 0,
    featured: false,
    featuredScore: 0,
  },
  {
    id: "5",
    name: "Viñedo Premium Rioja",
    category: "Agriculture",
    location: "La Rioja, España",
    image: "/premium-vineyard-wine-estate.jpg",
    pricePerTokenUSDT: 150,
    totalSupply: 8000,
    availableSupply: 6400,
    minBuy: 10,
    maxBuy: 400,
    apyEstimated: 7.5,
    riskNotes: "Inversión agrícola. Riesgo medio. Sujeto a condiciones climáticas y mercado del vino.",
    description:
      "Viñedo de 100 hectáreas con denominación de origen Rioja. Producción anual de 500,000 botellas de vino premium.",
    documents: [
      { id: "1", name: "Certificación DO", type: "PDF", url: "#" },
      { id: "2", name: "Historial de Producción", type: "PDF", url: "#" },
      { id: "3", name: "Contratos de Distribución", type: "PDF", url: "#" },
    ],
    status: "approved",
    ownerPromoterId: "promoter-3",
    salesUSDT: 240000,
    buyersCount: 16,
    featured: true,
    featuredScore: 80,
    featuredTag: "Limitado",
    highlightUntil: "2025-06-30T23:59:59Z",
  },
  {
    id: "6",
    name: "Edificio Oficinas Tech Hub",
    category: "Real Estate",
    location: "Málaga, España",
    image: "/modern-tech-office.png",
    pricePerTokenUSDT: 120,
    totalSupply: 12000,
    availableSupply: 9600,
    minBuy: 10,
    maxBuy: 600,
    apyEstimated: 8.9,
    riskNotes: "Inversión inmobiliaria comercial. Riesgo medio. Arrendado a empresas tecnológicas.",
    description:
      "Edificio de oficinas clase A en el Parque Tecnológico de Málaga. 15,000 m² distribuidos en 8 plantas.",
    documents: [
      { id: "1", name: "Contratos de Arrendamiento", type: "PDF", url: "#" },
      { id: "2", name: "Certificación Energética", type: "PDF", url: "#" },
      { id: "3", name: "Valoración Inmobiliaria", type: "PDF", url: "#" },
    ],
    status: "draft",
    ownerPromoterId: "promoter-3",
    salesUSDT: 0,
    buyersCount: 0,
    featured: false,
    featuredScore: 0,
  },
]

export const mockUser: User = {
  id: "user-1",
  walletAddress: null,
  kycVerified: false,
  purchases: [],
  role: null, // Can be changed to "admin", "investor", or "promoter" for testing
}

export const categories = ["All", "Real Estate", "Energy", "Hospitality", "Logistics", "Agriculture"]

export const mockOrders: Order[] = [
  {
    id: "order-1",
    projectId: "1",
    projectName: "Torre Residencial Madrid Centro",
    investorId: "investor-1",
    investorWallet: "0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb",
    quantity: 50,
    pricePerToken: 100,
    total: 5000,
    createdAt: "2025-01-15T10:30:00Z",
    status: "success",
  },
  {
    id: "order-2",
    projectId: "2",
    projectName: "Parque Solar Andalucía",
    investorId: "investor-2",
    investorWallet: "0x8ba1f109551bD432803012645Ac136ddd64DBA72",
    quantity: 100,
    pricePerToken: 50,
    total: 5000,
    createdAt: "2025-01-14T14:20:00Z",
    status: "success",
  },
  {
    id: "order-3",
    projectId: "3",
    projectName: "Hotel Boutique Barcelona",
    investorId: "investor-1",
    investorWallet: "0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb",
    quantity: 25,
    pricePerToken: 200,
    total: 5000,
    createdAt: "2025-01-13T09:15:00Z",
    status: "success",
  },
]

export const mockKycRecords: KycRecord[] = [
  {
    userId: "investor-1",
    userName: "Juan Pérez",
    role: "investor",
    status: "verified",
    submittedAt: "2025-01-01T10:00:00Z",
  },
  {
    userId: "investor-2",
    userName: "María García",
    role: "investor",
    status: "pending",
    submittedAt: "2025-01-10T15:30:00Z",
  },
  {
    userId: "promoter-1",
    userName: "Inversiones Madrid SL",
    role: "promoter",
    status: "verified",
    submittedAt: "2024-12-15T12:00:00Z",
  },
  {
    userId: "promoter-2",
    userName: "Green Energy Partners",
    role: "promoter",
    status: "verified",
    submittedAt: "2024-12-20T09:00:00Z",
  },
  {
    userId: "promoter-3",
    userName: "Rioja Investments",
    role: "promoter",
    status: "pending",
    submittedAt: "2025-01-05T11:00:00Z",
  },
]

export const mockMarketplaceFees: MarketplaceFees = {
  bps: 250, // 2.5%
  accruedUSDT: 28500,
}

export const mockPayouts: Payout[] = [
  {
    id: "payout-1",
    investorId: "investor-1",
    projectId: "1",
    projectName: "Torre Residencial Madrid Centro",
    amount: 425,
    date: "2025-01-01T00:00:00Z",
    status: "paid",
  },
  {
    id: "payout-2",
    investorId: "investor-1",
    projectId: "3",
    projectName: "Hotel Boutique Barcelona",
    amount: 270,
    date: "2025-01-01T00:00:00Z",
    status: "paid",
  },
]

export const mockAuditLogs: AuditLog[] = [
  {
    id: "log-1",
    action: "Proyecto aprobado",
    by: "Admin Principal",
    byRole: "admin",
    date: "2025-01-10T10:00:00Z",
    refId: "1",
    details: "Torre Residencial Madrid Centro",
  },
  {
    id: "log-2",
    action: "Proyecto creado",
    by: "Inversiones Madrid SL",
    byRole: "promoter",
    date: "2025-01-05T14:30:00Z",
    refId: "6",
    details: "Edificio Oficinas Tech Hub",
  },
  {
    id: "log-3",
    action: "Fee actualizado",
    by: "Admin Principal",
    byRole: "admin",
    date: "2025-01-03T09:00:00Z",
    details: "Fee cambiado de 200 bps a 250 bps",
  },
]

export const mockPromoterBalances: PromoterBalance[] = [
  {
    promoterId: "promoter-1",
    availableUSDT: 595000,
    pendingUSDT: 15000,
  },
  {
    promoterId: "promoter-2",
    availableUSDT: 242500,
    pendingUSDT: 7500,
  },
  {
    promoterId: "promoter-3",
    availableUSDT: 234000,
    pendingUSDT: 6000,
  },
]

export const mockInvestorHoldings = [
  {
    projectId: "1",
    projectName: "Torre Residencial Madrid Centro",
    category: "Real Estate",
    tokensOwned: 50,
    avgCost: 100,
    currentPrice: 100,
    totalValue: 5000,
    pnl: 0,
    pnlPercent: 0,
  },
  {
    projectId: "3",
    projectName: "Hotel Boutique Barcelona",
    category: "Hospitality",
    tokensOwned: 25,
    avgCost: 200,
    currentPrice: 200,
    totalValue: 5000,
    pnl: 0,
    pnlPercent: 0,
  },
  {
    projectId: "2",
    projectName: "Parque Solar Andalucía",
    category: "Energy",
    tokensOwned: 100,
    avgCost: 48,
    currentPrice: 50,
    totalValue: 5000,
    pnl: 200,
    pnlPercent: 4.17,
  },
]
